kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "bc-pipe-demo"
spec:
  source:
    git:
      uri: "https://github.com/mdanter/bc-pipe-demo"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: "FOO"
          value: "BAR"
