node('') {
          stage 'build'
	  print "FOO = ${FOO}"

	  def template = """
		the variable is called FOO, and it's defined in the build config which is referencing this file, the value of FOO is ${FOO}
"""
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'some-dc')
}
