kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "bc-pipe-demo"
  namespace: "admin-build"
spec:
  source:
    git:
      uri: "https://github.com/mdanter/bc-pipe-demo"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: app1/Jenkinsfile
      env:
        - name: "FOO"
          value: "BAR"
